# Generated by Django 5.2.7 on 2025-11-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Name',
            field=models.CharField(default='HEWHOSHALLNOTBENAMED', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='User_Interests',
            field=models.CharField(default='Nothing Really', max_length=100),
        ),
        migrations.AddField(
            model_name='visualnovels',
            name='author',
            field=models.CharField(default='Noone', max_length=100),
        ),
        migrations.AddField(
            model_name='visualnovels',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visualnovels',
            name='title',
            field=models.CharField(default='titlegoeshere', max_length=300),
        ),
    ]
