# Generated by Django 5.2.7 on 2025-11-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0003_users_name_users_user_interests_visualnovels_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='VisualNovels',
            new_name='VisualNovel',
        ),
    ]
