# Generated by Django 5.2.7 on 2025-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0004_rename_users_user_rename_visualnovels_visualnovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='available_on',
            field=models.CharField(default='unavailable', max_length=100),
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
