# Generated by Django 5.2.7 on 2025-11-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0005_visualnovel_available_on_visualnovel_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='HEWHOSHALLNOTBENAMED', max_length=100)),
                ('User_Interests', models.CharField(default='Nothing Really', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
