# Generated by Django 5.2.7 on 2025-11-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='vn_covers/'),
        ),
    ]
