# Generated by Django 5.2.7 on 2025-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0007_visualnovel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnovel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/vn_covers/'),
        ),
    ]
