# Generated by Django 5.2.7 on 2025-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0010_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualnovel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='visualnovel',
            name='genre',
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='author',
            field=models.ManyToManyField(blank=True, to='VNRealm.author'),
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='genre',
            field=models.ManyToManyField(blank=True, to='VNRealm.genre'),
        ),
    ]
