# Generated by Django 5.2.7 on 2025-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0011_remove_visualnovel_author_remove_visualnovel_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
