# Generated by Django 5.2.7 on 2025-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0012_availableon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualnovel',
            name='available_on',
        ),
        migrations.AddField(
            model_name='visualnovel',
            name='available_on',
            field=models.ManyToManyField(default='unavailable', to='VNRealm.availableon'),
        ),
    ]
