# Generated by Django 5.2.7 on 2025-11-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0013_remove_visualnovel_available_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualnovel',
            name='available_on',
            field=models.ManyToManyField(blank=True, to='VNRealm.availableon'),
        ),
    ]
