# Generated by Django 5.2.7 on 2025-11-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0015_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User_Interests',
            new_name='user_Interests',
        ),
    ]
