# Generated by Django 5.2.7 on 2025-11-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0016_rename_user_interests_userprofile_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='VNRealm.visualnovel'),
        ),
    ]
