# Generated by Django 5.2.7 on 2025-11-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0018_userprofile_is_adultplus_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VNRealm.visualnovel')),
            ],
            options={
                'unique_together': {('user', 'vn')},
            },
        ),
    ]
