# Generated by Django 5.2.7 on 2025-11-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VNRealm', '0019_playedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_Interests',
        ),
    ]
